#!/usr/bin/env python3
"""
PDF Report Generator
Creates comprehensive PDF reports combining all registration visualizations
"""

import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
from pathlib import Path
import numpy as np
from PIL import Image
import io


def create_comprehensive_pdf_report(output_dir: Path, stage_limit: str = "affine"):
    """
    Create a comprehensive PDF report combining all PNG visualizations
    
    Args:
        output_dir: Output directory containing debug_analysis folder
        stage_limit: Registration stage limit ("rigid", "affine", or "svffd")
    """
    
    print("\n📄 CREATING COMPREHENSIVE PDF REPORT")
    print("=" * 50)
    
    debug_dir = output_dir / "debug_analysis"
    pdf_path = output_dir / "registration_report.pdf"
    
    # Define the visualization files in logical order
    visualization_files = [
        ("side_by_side_common_coords_initial_alignment.png", "Initial Alignment - Before Registration"),
        ("side_by_side_common_coords_rigid_result.png", "Rigid Registration Result"),
        ("rigid_convergence_analysis.png", "Rigid Registration Convergence Analysis"),
        ("rigid_flow_field_analysis.png", "Rigid Flow Field and Vector Analysis"),
        ("rigid_grid_deformation.png", "Rigid Grid Deformation Visualization"),
    ]
    
    # Add affine visualizations if stage includes affine
    if stage_limit in ["affine", "svffd"]:
        visualization_files.extend([
            ("side_by_side_common_coords_affine_result.png", "Affine Registration Result"),
            ("affine_convergence_analysis.png", "Affine Registration Convergence Analysis"),
            ("affine_flow_field_analysis.png", "Affine Flow Field and Vector Analysis"),
            ("affine_grid_deformation.png", "Affine Grid Deformation with Movement Arrows"),
            ("affine_jacobian_determinant_map.png", "Affine Jacobian Determinant Map - Volume Change Analysis"),
            ("segmentation_overlay_progression.png", "Segmentation Transformation Progress"),
        ])
    
    # Add SVFFD visualizations if stage includes SVFFD
    if stage_limit == "svffd":
        visualization_files.extend([
            ("side_by_side_common_coords_svffd_result.png", "SVFFD Registration Result"),
            ("svffd_convergence_analysis.png", "SVFFD Registration Convergence Analysis"),
            ("svffd_flow_field_analysis.png", "SVFFD Flow Field and Deformation Analysis"),
            ("svffd_grid_deformation.png", "SVFFD Grid Deformation Visualization"),
        ])
    
    # Create PDF with all visualizations
    with PdfPages(pdf_path) as pdf:
        
        # Title page
        _create_title_page(pdf, stage_limit)
        
        # Add each visualization
        for i, (filename, title) in enumerate(visualization_files):
            file_path = debug_dir / filename
            
            if file_path.exists():
                print(f"   📊 Adding: {title}")
                _add_image_to_pdf(pdf, file_path, title, i + 1, len(visualization_files))
            else:
                print(f"   ⚠️  Missing: {filename}")
        
        # Summary page
        _create_summary_page(pdf, output_dir, stage_limit)
    
    print(f"✅ PDF Report created: {pdf_path}")
    print(f"   📄 Contains {len(visualization_files)} visualization pages")
    return pdf_path


def _create_title_page(pdf: PdfPages, stage_limit: str):
    """Create title page for the PDF report"""
    
    fig, ax = plt.subplots(figsize=(8.5, 11))
    ax.axis('off')
    
    # Title
    ax.text(0.5, 0.8, 'Medical Image Registration Report', 
            fontsize=24, fontweight='bold', ha='center', transform=ax.transAxes)
    
    # Subtitle
    stage_title = {
        "rigid": "Rigid Registration (6 DOF)",
        "affine": "Rigid + Affine Registration (6+9 DOF)", 
        "svffd": "Complete Pipeline: Rigid + Affine + SVFFD"
    }
    ax.text(0.5, 0.7, stage_title.get(stage_limit, f"{stage_limit.upper()} Registration"), 
            fontsize=16, ha='center', transform=ax.transAxes)
    
    # Pipeline description
    pipeline_text = f"""
Registration Pipeline Summary:
{'─' * 40}

• Stage Limit: {stage_limit.upper()}
• Coordinate System: Common world coordinates
• Resolution Preservation: Original image resolutions maintained
• Bidirectional Results: Both source→target and target→source

Registration Stages:
• Rigid (6 DOF): Translation + Rotation
• Affine (9 DOF): + Scaling (no shearing)
• SVFFD: + Non-linear deformation

Visualization Features:
• Side-by-side anatomical comparisons
• Convergence analysis with loss curves
• Flow field and vector analysis
• Grid deformation with movement arrows
• Multi-view anatomical overlays (sagittal, axial, coronal)

Generated by: deepali medical image registration system
Implementation: Clean modular architecture with comprehensive debugging
"""
    
    ax.text(0.1, 0.5, pipeline_text, fontsize=10, fontfamily='monospace',
            verticalalignment='top', transform=ax.transAxes,
            bbox=dict(boxstyle="round,pad=0.5", facecolor="lightgray", alpha=0.8))
    
    # Footer
    ax.text(0.5, 0.1, f'Report generated for sequential medical image registration', 
            fontsize=10, ha='center', style='italic', transform=ax.transAxes)
    
    pdf.savefig(fig, bbox_inches='tight')
    plt.close(fig)


def _add_image_to_pdf(pdf: PdfPages, image_path: Path, title: str, page_num: int, total_pages: int):
    """Add an image to the PDF with title and page number"""
    
    # Load and display the image with better quality settings
    img = Image.open(image_path)
    
    # Create figure with appropriate size
    fig, ax = plt.subplots(figsize=(11, 8.5))  # Landscape orientation
    
    # Display image with better interpolation and color preservation
    ax.imshow(img, interpolation='lanczos', aspect='equal')
    ax.axis('off')
    
    # Add title
    ax.set_title(title, fontsize=14, fontweight='bold', pad=20)
    
    # Add page number
    fig.text(0.95, 0.02, f'Page {page_num}/{total_pages}', 
             fontsize=10, ha='right', va='bottom')
    
    # Add filename reference
    fig.text(0.05, 0.02, f'Source: {image_path.name}', 
             fontsize=8, ha='left', va='bottom', style='italic')
    
    # Save with higher quality settings
    pdf.savefig(fig, bbox_inches='tight', dpi=300, 
                facecolor='white', edgecolor='none',
                metadata={'Creator': 'Medical Image Registration System'})
    plt.close(fig)


def _create_summary_page(pdf: PdfPages, output_dir: Path, stage_limit: str):
    """Create summary page with registration results"""
    
    fig, ax = plt.subplots(figsize=(8.5, 11))
    ax.axis('off')
    
    # Title
    ax.text(0.5, 0.95, 'Registration Summary', 
            fontsize=20, fontweight='bold', ha='center', transform=ax.transAxes)
    
    # Try to load and display registration results
    summary_text = f"""
Registration Results Summary:
{'=' * 50}

Stage Completed: {stage_limit.upper()}

Output Files Generated:
{'─' * 30}

📂 Transforms:
   • rigid_transform.pth
   • affine_transform.pth (if applicable)
   • svffd_transform.pth (if applicable)

📂 Final Results:
   • source_moved_to_target_*.nii.gz
   • target_moved_to_source_*.nii.gz
   • source_reference.nii.gz
   • target_reference.nii.gz

📂 Intermediate Results:
   • source_after_rigid_common.nii.gz
   • source_after_affine_common.nii.gz (if applicable)
   • source_after_svffd_common.nii.gz (if applicable)

📊 Debug Analysis:
   • Convergence analysis plots
   • Flow field visualizations
   • Grid deformation animations
   • Side-by-side comparisons
   • Vector movement arrows

Quality Metrics:
{'─' * 20}
• All registrations performed in common world coordinates
• Mutual field-of-view masking applied for robust alignment
• Multi-resolution pyramid optimization used
• Original image resolutions preserved in final outputs

Verification:
{'─' * 15}
Results can be verified in ITK-SNAP:
1. Load target_reference.nii.gz as main image
2. Overlay source_moved_to_target_*.nii.gz for alignment check
3. Compare with initial unregistered source for improvement assessment

Technical Implementation:
{'─' * 30}
• Library: deepali medical image registration
• Loss Functions: NCC (rigid), NMI (affine), Bending energy (SVFFD)
• Coordinate System: Common world coordinates with proper spacing
• Interpolation: Linear (images), Nearest neighbor (segmentations)
• Transform Chaining: Rigid → Affine → SVFFD sequential optimization
"""
    
    ax.text(0.05, 0.9, summary_text, fontsize=9, fontfamily='monospace',
            verticalalignment='top', transform=ax.transAxes,
            bbox=dict(boxstyle="round,pad=0.5", facecolor="lightblue", alpha=0.3))
    
    pdf.savefig(fig, bbox_inches='tight')
    plt.close(fig)